# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: isic2024
  - paths: default
  - logger: wandb
  - hydra: default
  - gbdt_params: default

# seed for random number generators in pytorch, numpy and python.random
seed: 0

optimized_metric: "test/pauc"

# null: run all CV folds; 0-4: run a single fold only
cv_fold: null
# fold: train CV fold(s) | tune: ensemble weight tuning | all_data: final model | feat_imp: feature importance
gbdt_stage: fold

wandb_summary_dir: ${paths.log_dir}wandb_cv
log_dir: ${paths.log_dir}/gbdt/runs/${gbdt_params.name}